/* ROOFTOP renderer: original, dependency-free WebGL. No external assets. */
'use strict';
window.R3=(()=>{
 const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
 function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
 function model(n){let a=n.yaw||0,b=n.rx||0,c=n.rz||0,C=Math.cos,S=Math.sin;let y=new Float32Array([C(a),0,-S(a),0,0,1,0,0,S(a),0,C(a),0,0,0,0,1]);let x=new Float32Array([1,0,0,0,0,C(b),S(b),0,0,-S(b),C(b),0,0,0,0,1]);let z=new Float32Array([C(c),S(c),0,0,-S(c),C(c),0,0,0,0,1,0,0,0,0,1]);let m=mul(mul(y,x),z);m[12]=n.x||0;m[13]=n.y||0;m[14]=n.z||0;return m}
 const norm=a=>{let l=Math.hypot(...a)||1;return a.map(v=>v/l)};
 const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
 const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
 function view(eye,target){let z=norm(eye.map((v,i)=>v-target[i])),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1])}
 function perspective(f,ar,near=.1,far=480){let t=1/Math.tan(f/2),d=1/(near-far);return new Float32Array([t/ar,0,0,0,0,t,0,0,0,0,(far+near)*d,-1,0,0,2*far*near*d,0])}
 const color=s=>{if(Array.isArray(s))return s;let h=s.replace('#','');return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255)};
 function vertex(out,p,n,c,uv=[0,0]){out.push(...p,...n,...c,...uv)}
 function quad(out,a,b,c,d,col){let n=norm(cross(b.map((x,i)=>x-a[i]),c.map((x,i)=>x-a[i]))),cc=color(col);[[a,[0,0]],[b,[1,0]],[c,[1,1]],[a,[0,0]],[c,[1,1]],[d,[0,1]]].forEach(([p,u])=>vertex(out,p,n,cc,u))}
 function box(out,x,y,z,w,h,d,col,yaw=0){let pts=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(p=>{let xx=p[0]*w/2,zz=p[2]*d/2;return [x+xx*Math.cos(yaw)+zz*Math.sin(yaw),y+p[1]*h/2,z-xx*Math.sin(yaw)+zz*Math.cos(yaw)]});[[4,5,6,7],[1,0,3,2],[0,4,7,3],[5,1,2,6],[3,7,6,2],[0,1,5,4]].forEach(f=>quad(out,...f.map(i=>pts[i]),col))}
 function cylinder(out,x,y,z,r,h,col,sides=12,r2=r){let cc=color(col);for(let i=0;i<sides;i++){let a=i/sides*Math.PI*2,b=(i+1)/sides*Math.PI*2,p=[x+Math.cos(a)*r,y-h/2,z+Math.sin(a)*r],q=[x+Math.cos(b)*r,y-h/2,z+Math.sin(b)*r],u=[x+Math.cos(b)*r2,y+h/2,z+Math.sin(b)*r2],v=[x+Math.cos(a)*r2,y+h/2,z+Math.sin(a)*r2];quad(out,q,p,v,u,col);vertex(out,[x,y+h/2,z],[0,1,0],cc);vertex(out,v,[0,1,0],cc);vertex(out,u,[0,1,0],cc);vertex(out,[x,y-h/2,z],[0,-1,0],cc);vertex(out,q,[0,-1,0],cc);vertex(out,p,[0,-1,0],cc)}}
 function transform(data,m){const out=[];for(let i=0;i<data.length;i+=11){let p=data.slice(i,i+3),n=data.slice(i+3,i+6);for(let r=0;r<3;r++)out.push(m[r]*p[0]+m[4+r]*p[1]+m[8+r]*p[2]+m[12+r]);let nn=norm([0,1,2].map(r=>m[r]*n[0]+m[4+r]*n[1]+m[8+r]*n[2]));out.push(...nn,...data.slice(i+6,i+11))}return out}
 function node(mesh=null,x=0,y=0,z=0){return {mesh,x,y,z,yaw:0,rx:0,rz:0,children:[],visible:true}}
 // Compatibility renderer: the same 3D scene and camera, without WebGL.
 class CanvasRenderer{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');if(!this.ctx)throw new Error('This browser cannot create a graphics canvas. Try opening the game in Safari or Chrome.');this.software=true;this.pixelCap=1;this.resize()}
  resize(){let d=Math.min(devicePixelRatio||1,this.pixelCap,1);this.canvas.width=Math.round(this.canvas.clientWidth*d);this.canvas.height=Math.round(this.canvas.clientHeight*d)}
  texture(canvas){return canvas}
  mesh(data,texture=null){const faces=[];for(let i=0;i<data.length;i+=33){faces.push({p:[data.slice(i,i+3),data.slice(i+11,i+14),data.slice(i+22,i+25)],n:data.slice(i+3,i+6),c:data.slice(i+6,i+9),uv:[data.slice(i+9,i+11),data.slice(i+20,i+22),data.slice(i+31,i+33)]})}return {faces,texture,count:data.length/11}}
  render(nodes,eye,target,fov=54){this.eye=eye;this.vp=mul(perspective(fov*Math.PI/180,this.canvas.width/this.canvas.height),view(eye,target));const g=this.ctx,W=this.canvas.width,H=this.canvas.height,vp=this.vp,out=[];g.clearRect(0,0,W,H);this.calls=0;
   const visit=(n,parent)=>{if(n.visible===false)return;const m=mul(parent,model(n));if(n.mesh){this.calls++;for(const f of n.mesh.faces){let p=f.p.map(p=>[0,1,2].map(r=>m[r]*p[0]+m[r+4]*p[1]+m[r+8]*p[2]+m[r+12]));let normal=[0,1,2].map(r=>m[r]*f.n[0]+m[r+4]*f.n[1]+m[r+8]*f.n[2]);if(!n.mesh.texture&&dot(normal,eye.map((v,i)=>v-p[0][i]))<-.001)continue;let verts=p.map((p,i)=>({v:[0,1,2,3].map(r=>vp[r]*p[0]+vp[r+4]*p[1]+vp[r+8]*p[2]+vp[r+12]),u:f.uv[i]})),cut=[];for(let j=0;j<3;j++){let a=verts[j],b=verts[(j+1)%3],ai=a.v[3]>=.15,bi=b.v[3]>=.15;if(ai)cut.push(a);if(ai!==bi){let t=(.15-a.v[3])/(b.v[3]-a.v[3]);cut.push({v:a.v.map((v,i)=>v+(b.v[i]-v)*t),u:a.u.map((v,i)=>v+(b.u[i]-v)*t)})}}if(cut.length<3)continue;let clip=cut.map(v=>v.v),xy=clip.map(v=>[(v[0]/v[3]*.5+.5)*W,(-v[1]/v[3]*.5+.5)*H]);if(xy.every(p=>p[0]<-2)||xy.every(p=>p[0]>W+2)||xy.every(p=>p[1]<-2)||xy.every(p=>p[1]>H+2))continue;let area=Math.abs((xy[1][0]-xy[0][0])*(xy[2][1]-xy[0][1])-(xy[1][1]-xy[0][1])*(xy[2][0]-xy[0][0]));if(area<.3)continue;let light=n.mesh.texture?1:.62+.38*Math.max(0,dot(normal,[-.452,.813,.362]));let distance=Math.hypot(...eye.map((v,i)=>v-p[0][i])),fog=Math.max(0,Math.min(1,(distance-100)/210));fog=fog*fog*(3-2*fog);let color=f.c.map((v,i)=>Math.round(255*(v*light*(1-fog)+[.65,.76,.81][i]*fog)));for(let j=1;j<cut.length-1;j++){let ids=[0,j,j+1];out.push({xy:ids.map(i=>xy[i]),depth:ids.reduce((a,i)=>a+clip[i][3],0)/3,color,uv:ids.map(i=>cut[i].u),tex:n.mesh.texture,floor:p.every(v=>v[1]<.3),height:p.reduce((a,v)=>a+v[1],0)/3})}}}
   for(const c of n.children)visit(c,m)};for(const n of nodes)visit(n,I());out.sort((a,b)=>a.floor!==b.floor?(a.floor?-1:1):a.floor?a.height-b.height:b.depth-a.depth);
   for(const f of out){const p=f.xy;g.beginPath();g.moveTo(...p[0]);g.lineTo(...p[1]);g.lineTo(...p[2]);g.closePath();if(f.tex){const uv=f.uv.map(t=>[t[0]*f.tex.width,(1-t[1])*f.tex.height]);let [u0,v0]=uv[0],[u1,v1]=uv[1],[u2,v2]=uv[2],det=u0*(v1-v2)+u1*(v2-v0)+u2*(v0-v1);if(Math.abs(det)<.001)continue;const coeff=q=>[(q[0]*(v1-v2)+q[1]*(v2-v0)+q[2]*(v0-v1))/det,(q[0]*(u2-u1)+q[1]*(u0-u2)+q[2]*(u1-u0))/det,(q[0]*(u1*v2-u2*v1)+q[1]*(u2*v0-u0*v2)+q[2]*(u0*v1-u1*v0))/det];let x=coeff(p.map(v=>v[0])),y=coeff(p.map(v=>v[1]));g.save();g.clip();g.transform(x[0],y[0],x[1],y[1],x[2],y[2]);g.drawImage(f.tex,0,0);g.restore()}else{g.fillStyle='rgb('+f.color.join(',')+')';g.fill();g.strokeStyle=g.fillStyle;g.lineWidth=.45;g.stroke()}}
  }
  project(p){let v=[...p,1],r=[0,1,2,3].map(i=>v.reduce((s,x,j)=>s+this.vp[j*4+i]*x,0));return {x:(r[0]/r[3]*.5+.5)*this.canvas.clientWidth,y:(-.5*r[1]/r[3]+.5)*this.canvas.clientHeight,visible:r[3]>.1&&Math.abs(r[0]/r[3])<1&&Math.abs(r[1]/r[3])<1}}
 }

 class Renderer{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!this.gl)return new CanvasRenderer(canvas);const g=this.gl;
   const vs=`attribute vec3 aP,aN,aC;attribute vec2 aU;uniform mat4 uM,uVP;uniform vec3 uEye;varying vec3 vC;varying vec2 vU;varying float vFog;uniform float uFlat;void main(){vec4 p=uM*vec4(aP,1.);vec3 n=normalize(mat3(uM)*aN);float light=.62+.38*max(0.,dot(n,normalize(vec3(-.5,.9,.4))));vC=aC*mix(light,1.,uFlat);vU=aU;vFog=smoothstep(100.,310.,distance(p.xyz,uEye));gl_Position=uVP*p;}`;
   const fs=`precision mediump float;varying vec3 vC;varying vec2 vU;varying float vFog;uniform sampler2D uTex;uniform float uUseTex;void main(){vec4 t=mix(vec4(1.),texture2D(uTex,vU),uUseTex);if(t.a<.05)discard;gl_FragColor=vec4(mix(vC*t.rgb,vec3(.65,.76,.81),vFog),t.a);}`;
   const sh=(type,src)=>{let s=g.createShader(type);g.shaderSource(s,src);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(s));return s};this.p=g.createProgram();g.attachShader(this.p,sh(g.VERTEX_SHADER,vs));g.attachShader(this.p,sh(g.FRAGMENT_SHADER,fs));g.linkProgram(this.p);if(!g.getProgramParameter(this.p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(this.p));g.useProgram(this.p);
   this.a={};['aP','aN','aC','aU'].forEach(k=>this.a[k]=g.getAttribLocation(this.p,k));this.u={};['uM','uVP','uEye','uTex','uUseTex','uFlat'].forEach(k=>this.u[k]=g.getUniformLocation(this.p,k));g.enable(g.DEPTH_TEST);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.clearColor(0,0,0,0);this.white=this.texture(Object.assign(document.createElement('canvas'),{width:1,height:1}));this.pixelCap=1.5;this.resize();
  }
  resize(){let w=this.canvas.clientWidth,h=this.canvas.clientHeight,d=Math.min(devicePixelRatio||1,this.pixelCap);this.canvas.width=Math.round(w*d);this.canvas.height=Math.round(h*d);this.gl.viewport(0,0,this.canvas.width,this.canvas.height)}
  mesh(data,texture=null){let g=this.gl,b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);return {buffer:b,count:data.length/11,texture}}
  texture(canvas){let g=this.gl,t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,true);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,canvas);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);return t}
  render(nodes,eye,target,fov=54){let g=this.gl;this.eye=eye;this.vp=mul(perspective(fov*Math.PI/180,this.canvas.width/this.canvas.height),view(eye,target));g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.p);g.uniformMatrix4fv(this.u.uVP,false,this.vp);g.uniform3fv(this.u.uEye,eye);g.uniform1i(this.u.uTex,0);this.calls=0;const draw=(n,parent)=>{if(n.visible===false)return;let m=mul(parent,model(n));if(n.mesh){let b=n.mesh;g.bindBuffer(g.ARRAY_BUFFER,b.buffer);[['aP',3,0],['aN',3,12],['aC',3,24],['aU',2,36]].forEach(([name,size,off])=>{g.enableVertexAttribArray(this.a[name]);g.vertexAttribPointer(this.a[name],size,g.FLOAT,false,44,off)});g.uniformMatrix4fv(this.u.uM,false,m);g.uniform1f(this.u.uUseTex,b.texture?1:0);g.uniform1f(this.u.uFlat,b.texture?1:0);g.bindTexture(g.TEXTURE_2D,b.texture||this.white);g.drawArrays(g.TRIANGLES,0,b.count);this.calls++}for(const c of n.children)draw(c,m)};for(const n of nodes)draw(n,I())}
  project(p){let v=[...p,1],r=[0,1,2,3].map(i=>v.reduce((s,x,j)=>s+this.vp[j*4+i]*x,0));return {x:(r[0]/r[3]*.5+.5)*this.canvas.clientWidth,y:(-.5*r[1]/r[3]+.5)*this.canvas.clientHeight,visible:r[3]>.1&&Math.abs(r[0]/r[3])<1&&Math.abs(r[1]/r[3])<1}}
 }
 return {I,mul,model,box,cylinder,quad,transform,node,Renderer,color};
})();
