/* ROOFTOP 0.3.0 — mobile-first playable vertical slice. */
'use strict';
(()=>{const $=id=>document.getElementById(id);function fail(e){$('errorText').textContent=e.message||String(e);$('error').classList.remove('hidden')}
try{
 if(!window.R3||!window.buildRooftopWorld)throw new Error('A game file did not load. Refresh to try again.');
 const r=new R3.Renderer($('game')),w=buildRooftopWorld(r),player=w.player,truck=w.vehicle;
 const V='0.3.0',RUNKEY='rooftop-v3-run',PROFILEKEY='rooftop-v3-profile';
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),angle=a=>Math.atan2(Math.sin(a),Math.cos(a));
 const touch=navigator.maxTouchPoints>0||matchMedia('(pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 const conditions=[{id:'drain',title:'Drain assembly',x:58,z:-40,correct:'maintenance',explain:'Leaves are obstructing the drain. Document it and recommend drainage maintenance.'},{id:'seam',title:'Membrane seam',x:43,z:-30,correct:'repair',explain:'The membrane seam is visibly open. A targeted repair is appropriate; this alone does not prove the reported leak source.'},{id:'patch',title:'Previous repair',x:59,z:-24,correct:'monitor',explain:'This patch appears sound. Record its condition without selling an unnecessary repair.'}];
 const recs={maintenance:'Routine maintenance',repair:'Targeted repair',monitor:'Sound — monitor',investigate:'Further investigation'};
 let storageWarned=false;function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{if(!storageWarned){storageWarned=true;toast('Saving is unavailable. You can still play this session.')}return false}}
 const rawProfile=read(PROFILEKEY)||{};let profile={cash:Number.isFinite(rawProfile.cash)?clamp(rawProfile.cash,0,1e9):2500,rep:Number.isFinite(rawProfile.rep)?clamp(rawProfile.rep,0,100):50,best:Number.isFinite(rawProfile.best)?clamp(rawProfile.best,0,100):0,paid:Array.isArray(rawProfile.paid)?rawProfile.paid.filter(x=>typeof x==='string').slice(-40):[],sound:rawProfile.sound===true,low:rawProfile.low===true};
 let run=null,started=false,modal=false,photoMode=false,focus=null,photoYaw=.6,lastShot=null,photos=new Map(),auto=false,routeIndex=0,speed=0,camYaw=1.55,camPitch=.46,dragTime=0,clock=0,walkTime=0,lastSave=0,lastFrame=performance.now(),currentContext=null;
 let keys={},joy={x:0,y:0,id:null},braking=false,cameraPointer=null,toastUntil=0,eye=[-84,37,-4],target=[-25,1,-18],db=null;
 const route=[{x:-37,z:-5},{x:20,z:-5},{x:44,z:-10}],park={x:44,z:-10},hatch={x:32,z:-17},roofHatch={x:32,z:-20.6};
 const newRun=()=>({version:3,id:'shift-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),onRoof:false,talked:false,arrived:false,mode:'walk',complete:false,findings:{},seconds:0,score:0,pay:0,repChange:0});
 const candidate=read(RUNKEY);let saved=candidate&&candidate.version===3&&typeof candidate.id==='string'&&candidate.findings&&typeof candidate.findings==='object'?candidate:null;
 function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastUntil=performance.now()+3300}
 function resetInput(){keys={};joy.x=joy.y=0;joy.id=null;braking=false;cameraPointer=null;$('stick').style.transform='translate(-50%,-50%)'}
 function save(){if(!run)return;run.position={x:player.x,z:player.z};run.truck={x:truck.x,z:truck.z,yaw:truck.yaw};run.camera=camYaw;store(RUNKEY,run)}
 // Photos live in IndexedDB, separate from the small versioned progress record.
 const dbReady=new Promise(resolve=>{try{const q=indexedDB.open('rooftop-v3-evidence',1);q.onupgradeneeded=()=>q.result.createObjectStore('photos');q.onsuccess=()=>{db=q.result;resolve()};q.onerror=()=>resolve();q.onblocked=()=>resolve()}catch{resolve()}});
 async function writePhoto(id,url){await dbReady;if(!db){toast('Photo saved for this session only. Browser storage is unavailable.');return}await new Promise(resolve=>{try{let tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(url,run.id+'/'+id);tx.oncomplete=resolve;tx.onerror=()=>{toast('Photo storage is full. This photo is session-only.');resolve()}}catch{resolve()}})}
 async function loadPhotos(){await dbReady;if(!db)return;await Promise.all(conditions.map(f=>new Promise(resolve=>{try{const q=db.transaction('photos').objectStore('photos').get(run.id+'/'+f.id);q.onsuccess=()=>{if(typeof q.result==='string')photos.set(f.id,q.result);resolve()};q.onerror=resolve}catch{resolve()}})))}
 function clearPhotos(){if(!db)return;try{db.transaction('photos','readwrite').objectStore('photos').clear()}catch{}}
 function updateStats(){$('cash').textContent='$'+Math.floor(profile.cash).toLocaleString();$('soundState').textContent=profile.sound?'ON':'OFF';$('sound').setAttribute('aria-label',profile.sound?'Mute sound':'Turn sound on')}
 let audio=null,engineOsc=null,engineGain=null;function audioInit(){try{if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();engineOsc=audio.createOscillator();engineGain=audio.createGain();engineOsc.type='triangle';engineOsc.connect(engineGain);engineGain.connect(audio.destination);engineGain.gain.value=0;engineOsc.start()}if(audio.state==='suspended')audio.resume()}catch{}}
 function chime(success=true){if(!profile.sound)return;audioInit();if(!audio)return;[0,1,2].forEach(i=>{let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=(success?[440,554,659]:[330,294,247])[i];o.connect(g);g.connect(audio.destination);let t=audio.currentTime+i*.07;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.06,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.start(t);o.stop(t+.2)})}
 function sheet(tag,title,body,buttons){modal=true;resetInput();$('sheetTag').textContent=tag;$('sheetTitle').textContent=title;$('sheetBody').innerHTML=body;$('sheetActions').innerHTML='';for(const item of buttons){let b=document.createElement('button');b.className=item.secondary?'secondary':'primary';b.textContent=item.label;b.onclick=item.fn;$('sheetActions').appendChild(b)}$('sheet').classList.remove('hidden');$('sheet').querySelector('.sheet-content').scrollTop=0;setTimeout(()=>$('sheetActions').querySelector('button')?.focus({preventScroll:true}),0)}
 function closeSheet(){modal=false;$('sheet').classList.add('hidden');resetInput()}
 async function start(resume=false){audioInit();photos.clear();run=resume&&saved?saved:newRun();if(!resume){player.x=-47.8;player.z=-12.5;truck.x=-50;truck.z=-10;truck.yaw=Math.PI/2;camYaw=1.55;clearPhotos()}else{let p=run.position||{},t=run.truck||{};player.x=Number.isFinite(p.x)?clamp(p.x,-125,125):-47;player.z=Number.isFinite(p.z)?clamp(p.z,-125,125):-13.4;truck.x=Number.isFinite(t.x)?clamp(t.x,-125,125):-50;truck.z=Number.isFinite(t.z)?clamp(t.z,-125,125):-10;truck.yaw=Number.isFinite(t.yaw)?t.yaw:Math.PI/2;camYaw=Number.isFinite(run.camera)?run.camera:1.55;await loadPhotos()}
 run.mode=run.mode==='drive'&&!run.onRoof?'drive':'walk';run.complete=!!run.complete;speed=0;started=true;modal=false;photoMode=false;auto=false;focus=null;player.y=run.onRoof?w.roofY+.04:.14;player.visible=run.mode==='walk';$('titleScreen').classList.add('hidden');$('hud').classList.remove('hidden');$('sheet').classList.add('hidden');resetInput();updateStats();setCamera(1);save();if(run.complete)finishScreen();else toast(resume?'Shift resumed. Your company is waiting.':touch?'Left thumb moves. Drag the world to look. Tap GET IN.':'WASD to move. Drag to look. E to interact.');}
 function groundBlocked(x,z,radius){if(Math.abs(x)>128||Math.abs(z)>124)return true;return w.obstacles.some(o=>Math.abs(x-o.x)<o.w/2+radius&&Math.abs(z-o.z)<o.d/2+radius)}
 function roofBlocked(x,z){return x<29.85||x>66.15||z<-49.15||z>-18.85||w.roofBlocks.slice(0,4).some(o=>Math.abs(x-o.x)<o.w/2+.35&&Math.abs(z-o.z)<o.d/2+.35)}
 function context(){if(!run||run.complete)return null;if(photoMode)return {type:'snap',label:'SHUTTER',icon:'◎'};if(run.mode==='drive')return {type:'exit',label:'GET OUT',icon:'↙'};if(run.onRoof){let f=conditions.filter(f=>dist(player,f)<3.1).sort((a,b)=>dist(player,a)-dist(player,b))[0];if(f)return {type:'inspect',label:run.findings[f.id]?'RECHECK':'INSPECT',icon:'◎',f};if(dist(player,roofHatch)<2.35)return {type:'down',label:'GO DOWN',icon:'↓'};return null}if(run.talked&&dist(player,hatch)<3)return {type:'up',label:'ROOF ACCESS',icon:'↑'};if(dist(player,w.manager)<2.8&&run.arrived)return {type:'talk',label:run.talked?'TALK AGAIN':'CHECK IN',icon:'…'};if(dist(player,truck)<4.1)return {type:'enter',label:'GET IN',icon:'↗'};return null}
 function interact(){if(!started||modal||run.complete)return;let c=context();if(!c){toast(run.onRoof?'Walk closer to a roof detail to inspect it.':'Move closer to your truck or the job-site contact.');return}if(c.type==='enter'){run.mode='drive';player.visible=false;camYaw=truck.yaw;camPitch=.35;save();toast('Follow the route to Westgate. AUTO DRIVE is optional.')}if(c.type==='exit'){if(Math.abs(speed)>.7){toast('Hold STOP, then get out once the truck stops.');return}let options=[{x:truck.x+3*Math.cos(truck.yaw),z:truck.z-3*Math.sin(truck.yaw)},{x:truck.x-3*Math.cos(truck.yaw),z:truck.z+3*Math.sin(truck.yaw)}];let p=options.find(p=>!groundBlocked(p.x,p.z,.35));if(!p){toast('Park somewhere with room to open the door.');return}run.mode='walk';player.visible=true;player.x=p.x;player.z=p.z;player.y=.14;speed=0;auto=false;camPitch=.47;save()}
 if(c.type==='talk')sheet('JORDAN / PROPERTY MANAGER','“It only leaks when it rains.”','<p>“Water showed up above aisle six. The last guy called it a permanent temporary repair.”</p><p>The weather has cleared. Use the designated roof access, inspect the drain, seams and existing repairs, and bring back a useful report.</p><p class="note">This game uses simplified protected work areas. It is not safety training.</p>',[{label:'GOT IT — CHECK THE ROOF',fn:()=>{run.talked=true;closeSheet();save();toast('Roof access is beside the entrance. Look for the yellow marker.')}}]);
 if(c.type==='up'){run.onRoof=true;player.x=34.7;player.z=-21;player.y=w.roofY+.04;camYaw=Math.PI;camPitch=.6;save();chime();toast('Inspect at least two details. Three accurate findings earns the best score.')}
 if(c.type==='down'){run.onRoof=false;player.x=32;player.z=-15.8;player.y=.14;camYaw=0;save()}
 if(c.type==='inspect'){focus=c.f;photoMode=true;photoYaw=.6;camPitch=.48;resetInput();setCamera(1);toast('Take a photo, then choose an honest recommendation.')}
 if(c.type==='snap')capture();}
 function capture(){if(!focus||!photoMode)return;setCamera(1);r.render(w.nodes,eye,target,54);let projected=r.project([focus.x,w.roofY+.2,focus.z]);if(!projected.visible){toast('Keep the roof detail in frame.');return}let c=document.createElement('canvas');c.width=384;c.height=216;let ctx=c.getContext('2d'),src=$('game'),sw=src.width,sh=src.height;let cutH=Math.min(sh,sw*9/16),cutW=cutH*16/9;ctx.drawImage(src,(sw-cutW)/2,(sh-cutH)/2,cutW,cutH,0,0,384,216);lastShot=c.toDataURL('image/jpeg',.78);chime();classify()}
 function classify(){let choice=run.findings[focus.id]?.rec||'',f=focus;sheet('PHOTO CAPTURED / '+f.title.toUpperCase(),'What’s your recommendation?',`<img class="evidence-img" src="${lastShot}" alt="Your photograph of the roof detail"><p>Make the call. Not every old repair needs replacing.</p><div id="choices"></div>`,[{label:'ADD TO FIELD REPORT',fn:async()=>{if(!choice){toast('Choose a recommendation first.');return}const url=lastShot;photos.set(f.id,url);run.findings[f.id]={rec:choice};await writePhoto(f.id,url);save();closeSheet();photoMode=false;focus=null;camPitch=.58;chime();toast(Object.keys(run.findings).length+'/3 findings documented. Keep looking, or open FIELD REPORT.')}},{label:'RETAKE PHOTO',secondary:true,fn:()=>closeSheet()}]);for(const [id,text] of Object.entries(recs)){let b=document.createElement('button');b.className='choice'+(choice===id?' selected':'');b.textContent=text;b.setAttribute('aria-pressed',choice===id?'true':'false');b.onclick=()=>{choice=id;for(const e of $('choices').children){e.classList.toggle('selected',e===b);e.setAttribute('aria-pressed',e===b?'true':'false')}};$('choices').appendChild(b)}}
 function report(){if(!started||run.complete)return;photoMode=false;focus=null;let items=conditions.filter(f=>run.findings[f.id]),body='<p>Your photos. Your recommendations. No invented findings.</p>';for(const f of items)body+=`<div class="report-row">${photos.has(f.id)?`<img src="${photos.get(f.id)}" alt="Inspection evidence">`:'<span class="note">Photo unavailable</span>'}<div><h3>${f.title}</h3><p>${recs[run.findings[f.id].rec]||'No recommendation'}</p></div></div>`;if(!items.length)body+='<p>No findings yet. Explore the roof and tap INSPECT near a detail.</p>';body+=`<p class="note">${items.length}/3 details documented. Photo evidence and appropriate recommendations determine the result. Currency is fictional.</p>`;sheet('FIELD REPORT / WESTGATE','Let your work do the talking.',body,[{label:items.length>=2?'SUBMIT REPORT →':'KEEP INSPECTING — MINIMUM 2 FINDINGS',fn:()=>{if(items.length<2)closeSheet();else submit()}},{label:'BACK TO THE ROOF',secondary:true,fn:closeSheet}])}
 function submit(){if(run.complete)return;let score=10;for(const f of conditions){let e=run.findings[f.id];if(e){if(photos.has(f.id))score+=10;if(e.rec===f.correct)score+=20;else if(e.rec==='investigate'&&f.id!=='patch')score+=8}}run.score=clamp(score,0,100);run.pay=score>=80?450:score>=60?375:250;run.repChange=score>=90?6:score>=70?3:score>=50?0:-3;run.complete=true;if(!profile.paid.includes(run.id)){profile.cash+=run.pay;profile.rep=clamp(profile.rep+run.repChange,0,100);profile.best=Math.max(profile.best,run.score);profile.paid.push(run.id);profile.paid=profile.paid.slice(-40);store(PROFILEKEY,profile)}save();updateStats();chime(score>=70);finishScreen()}
 function finishScreen(){let grade=run.score>=90?'ROOF-SHARP OPERATOR':run.score>=70?'SOLID FIRST SHIFT':'BACK TO THE FIELD';let body=`<div class="score">${run.score}<small> / 100</small></div><div class="score-grade">${grade}</div><div class="earnings"><div><span>INSPECTION EARNINGS</span><b>$${run.pay}</b></div><div><span>REPUTATION</span><b>${run.repChange>=0?'+':''}${run.repChange}</b></div></div><p>${run.score>=80?'Jordan wants a quote for the follow-up work. That’s how you build a business.':'The report is in. More complete evidence and balanced recommendations will win more trust.'}</p>`;for(const f of conditions){let e=run.findings[f.id];body+=`<p class="note"><b>${e?(e.rec===f.correct?'✓':'△'):'—'} ${f.title}:</b> ${e?f.explain:'Not documented this shift.'}</p>`}body+=`<p class="note">Personal best on this device: ${profile.best}/100. Prototype — fictional earnings, not professional advice.</p>`;sheet('SHIFT COMPLETE / INVOICE PAID','Another roof. Another opportunity.',body,[{label:'PLAY ANOTHER SHIFT',fn:()=>{closeSheet();start(false)}},{label:'SHARE YOUR SCORE',secondary:true,fn:share}])}
 async function share(){const url=new URL(location.href);url.search='?v=0.3.0';url.hash='';const text=`I scored ${run.score}/100 on ROOFTOP: Owner Operator. Can you run a roofing company?`;try{if(navigator.share){await navigator.share({title:'ROOFTOP — '+run.score+'/100',text,url:url.href});return}if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(text+' '+url.href);toast('Score and game link copied.');return}}catch(e){if(e.name==='AbortError')return}sheet('SHARE YOUR SCORE','Challenge another roofer.',`<p>${text}</p><textarea id="shareText" aria-label="Score and link" style="width:100%;min-height:100px;font:14px sans-serif;padding:12px"></textarea>`,[{label:'BACK TO RESULTS',fn:finishScreen}]);$('shareText').value=text+' '+url.href;$('shareText').select()}
 function pause(){if(!started)return;if(run.complete){finishScreen();return}sheet('PAUSED / ROOFTOP '+V,'Take five.',`<p>Move with the thumbstick. Drag the world to look. Use the big yellow action button when you get close.</p><p>Desktop: WASD move / steer. E interact. Space brake. Tab report. Escape pause.</p><p class="note">Original generated artwork. No sign-in or tracking. Progress is stored on this device. This is entertainment, not roofing or safety training.</p>`,[{label:'BACK TO WORK',fn:closeSheet},{label:profile.low?'QUALITY: BATTERY SAVER → STANDARD':'QUALITY: STANDARD → BATTERY SAVER',secondary:true,fn:()=>{profile.low=!profile.low;r.pixelCap=profile.low?1:1.5;r.resize();store(PROFILEKEY,profile);pause()}},{label:'RESET CAMERA / GET UNSTUCK',secondary:true,fn:()=>{speed=0;auto=false;if(run.onRoof){player.x=34.7;player.z=-21;camYaw=Math.PI}else{truck.x=run.arrived?44:-50;truck.z=run.arrived?-10:-10;truck.yaw=Math.PI/2;player.x=truck.x;player.z=truck.z-3.4;camYaw=Math.PI/2}closeSheet();save();toast('Returned to a safe spot. Your findings are intact.')}}])}
 function advance(dt){const h=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+joy.x;const v=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)-joy.y;const a=clamp(h,-1,1),t=clamp(v,-1,1);if(run.mode==='drive'){
  if(auto&&(Math.abs(a)>.12||Math.abs(t)>.12||braking))auto=false;
  if(auto){let p=route[routeIndex];if(!p){auto=false;speed=0;run.arrived=true;save();toast('Parked at Westgate. Tap GET OUT and meet Jordan.')}else{let d=dist(truck,p);if(d<1.4)routeIndex++;let desired=Math.atan2(p.x-truck.x,p.z-truck.z),delta=angle(desired-truck.yaw);truck.yaw+=clamp(delta,-1.8*dt,1.8*dt);let targetSpeed=Math.abs(delta)>1?4:routeIndex===route.length-1?Math.min(11,d*1.8+1):12;speed+=clamp(targetSpeed-speed,-12*dt,7*dt)}}
  else{speed=clamp(speed+t*8*dt,-5,14);if(Math.abs(t)<.08)speed*=Math.pow(.08,dt);if(keys.Space||braking)speed*=Math.pow(.00002,dt);truck.yaw-=a*1.75*dt*clamp(speed/7,-1,1)}
  if(Math.abs(speed)<.035)speed=0;let nx=truck.x+Math.sin(truck.yaw)*speed*dt,nz=truck.z+Math.cos(truck.yaw)*speed*dt;if(!groundBlocked(nx,nz,1.55)&&Math.hypot(nx-w.manager.x,nz-w.manager.z)>2.2){truck.x=nx;truck.z=nz}else{speed=0;if(auto){auto=false;toast('Route blocked. Steer around the obstacle, or use Reset in Pause.')}}
  truck.wheels.forEach(wh=>wh.rx+=speed*dt/.55);if(performance.now()-dragTime>1800)camYaw+=angle(truck.yaw-camYaw)*(1-Math.exp(-dt*3));if(!run.arrived&&dist(truck,park)<7&&Math.abs(speed)<.7){run.arrived=true;save();toast('You made it. Meet Jordan by the entrance.')}
 }else{let len=Math.hypot(a,t);if(len>.06){let mag=Math.min(1,len),vx=(Math.sin(camYaw)*t-Math.cos(camYaw)*a)/len*mag*5.5*dt,vz=(Math.cos(camYaw)*t+Math.sin(camYaw)*a)/len*mag*5.5*dt;const blocked=run.onRoof?roofBlocked:(x,z)=>groundBlocked(x,z,.36)||dist({x,z},truck)<1.55;
  if(!blocked(player.x+vx,player.z))player.x+=vx;if(!blocked(player.x,player.z+vz))player.z+=vz;let facing=Math.atan2(vx,vz);player.yaw+=angle(facing-player.yaw)*Math.min(1,dt*14);walkTime+=dt*10*mag;player.legs[0].rx=Math.sin(walkTime)*.5;player.legs[1].rx=-Math.sin(walkTime)*.5;player.arms[0].rx=-Math.sin(walkTime)*.42;player.arms[1].rx=Math.sin(walkTime)*.42;
 }else{for(const l of [...player.legs,...player.arms])l.rx*=Math.pow(.004,dt)}player.y=(run.onRoof?w.roofY+.04:.14)+(reduced?0:Math.sin(walkTime*2)*.022*Math.min(1,Math.hypot(a,t)))}
 }
 function setCamera(mix){let wantEye,wantTarget;if(!started){wantEye=[-64+Math.sin(clock*.11)*3,8.2,9];wantTarget=[-41,2.1,-20]}
 else if(photoMode&&focus){wantTarget=[focus.x,w.roofY+.15,focus.z];wantEye=[focus.x+Math.sin(photoYaw)*4.5,w.roofY+3.5,focus.z+Math.cos(photoYaw)*4.5]}
 else{let p=run.mode==='drive'?truck:player,drive=run.mode==='drive',d=drive?10.5:run.onRoof?6.8:6;wantTarget=[p.x,p.y+(drive?1.3:1.4),p.z];wantEye=[p.x-Math.sin(camYaw)*d,Math.max((run.onRoof?w.roofY:0)+1.8,wantTarget[1]+d*Math.sin(camPitch)),p.z-Math.cos(camYaw)*d];
  for(let step=1;step<18;step++){let t=step/18,x=wantTarget[0]+(wantEye[0]-wantTarget[0])*t,y=wantTarget[1]+(wantEye[1]-wantTarget[1])*t,z=wantTarget[2]+(wantEye[2]-wantTarget[2])*t;let hit=w.obstacles.some(o=>y<o.h+.8&&Math.abs(x-o.x)<o.w/2+.2&&Math.abs(z-o.z)<o.d/2+.2);if(hit){let safe=Math.max(.15,(step-1)/18);wantEye=wantTarget.map((v,i)=>v+(wantEye[i]-v)*safe);break}}
 }eye=eye.map((v,i)=>v+(wantEye[i]-v)*mix);target=target.map((v,i)=>v+(wantTarget[i]-v)*mix)}
 function radar(){let c=$('radar'),g=c.getContext('2d'),p=run.mode==='drive'?truck:player,s=run.onRoof?5.3:1.35,center=run.onRoof?{x:48,z:-34}:p;const xx=x=>120+(x-center.x)*s,zz=z=>120+(z-center.z)*s;g.clearRect(0,0,240,240);g.fillStyle='#234252';g.fillRect(0,0,240,240);g.strokeStyle='#60727b';g.lineWidth=16*s;for(const z of [0]){g.beginPath();g.moveTo(0,zz(z));g.lineTo(240,zz(z));g.stroke()}for(const x of [-35,78]){g.beginPath();g.moveTo(xx(x),0);g.lineTo(xx(x),240);g.stroke()}for(const o of w.obstacles){g.fillStyle=o.x===48?'#a0b8b4':'#455b66';g.fillRect(xx(o.x-o.w/2),zz(o.z-o.d/2),o.w*s,o.d*s)}if(!run.onRoof){g.strokeStyle='#f0d265';g.lineWidth=3;g.setLineDash([5,4]);g.beginPath();g.moveTo(xx(-50),zz(-10));for(const p of route)g.lineTo(xx(p.x),zz(p.z));g.stroke();g.setLineDash([]);g.fillStyle='#f0d265';g.beginPath();g.arc(xx(park.x),zz(park.z),6,0,Math.PI*2);g.fill()}else{for(const f of conditions)if(run.findings[f.id]||dist(player,f)<7){g.fillStyle=run.findings[f.id]?'#f0d265':'#e2e7d1';g.beginPath();g.arc(xx(f.x),zz(f.z),4,0,6.283);g.fill()}for(const b of w.roofBlocks.slice(0,4)){g.fillStyle='#526e7b';g.fillRect(xx(b.x-b.w/2),zz(b.z-b.d/2),b.w*s,b.d*s)}}
 let a=run.mode==='drive'?truck.yaw:player.yaw;g.save();g.translate(xx(p.x),zz(p.z));g.rotate(-a);g.fillStyle='#fff9e2';g.strokeStyle='#182c3c';g.lineWidth=2;g.beginPath();g.moveTo(0,11);g.lineTo(-7,-7);g.lineTo(0,-4);g.lineTo(7,-7);g.closePath();g.fill();g.stroke();g.restore();g.font='bold 17px sans-serif';g.fillStyle='#f5f1da';g.fillText('N',112,24)}
 function hud(){if(!started||!run)return;let count=Object.keys(run.findings).length,stage=run.onRoof?3:run.talked?2:run.arrived?1:0;let objective=run.onRoof?'Walk the roof. Inspect drains, seams and previous repairs.':run.talked?'Use the marked roof access beside the entrance.':run.arrived?'Meet Jordan by the Westgate entrance.':run.mode==='drive'?'Drive to Westgate. Follow the yellow route.':'Get into your work truck.';if(count>=2&&run.onRoof)objective=count===3?'Three findings. Open FIELD REPORT to finish.':'Two findings recorded. Find the third, or submit your report.';$('objective').textContent=objective;$('smallStatus').innerHTML=run.onRoof?'EVIDENCE <b>'+count+' / 3</b>':'INSPECTION FEE <b>$450</b>';
 [...$('progress').children].forEach((e,i)=>e.classList.toggle('done',i<=stage));const driving=run.mode==='drive';$('speed').classList.toggle('hidden',!driving||photoMode);$('speed').querySelector('strong').textContent=Math.round(Math.abs(speed)*3.6);$('brake').classList.toggle('hidden',!driving);$('route').classList.toggle('hidden',!driving||run.arrived);$('route').textContent=auto?'✕ CANCEL AUTO DRIVE':'↗ AUTO DRIVE';$('reportButton').classList.toggle('hidden',!run.talked||photoMode);$('evidenceCount').textContent=count+' / 3';$('crosshair').classList.toggle('hidden',!photoMode);$('cameraHint').classList.toggle('hidden',!photoMode);$('cancelCamera').classList.toggle('hidden',!photoMode);$('joystick').classList.toggle('hidden',photoMode);$('moveLabel').classList.toggle('hidden',photoMode);$('moveLabel').textContent=driving?'DRIVE':'MOVE';$('lookHint').textContent=photoMode?'':driving?(touch?'Thumbstick to steer / accelerate':'WASD drive · Space brake · E exit'):(touch?'Drag the world to look':'WASD move · Drag to look · E interact');currentContext=context();$('actionText').textContent=currentContext?.label||'EXPLORE';$('actionIcon').textContent=currentContext?.icon||'⌖';$('action').disabled=!currentContext;
 let point=null,name='';if(photoMode){$('pin').classList.add('hidden')}else{if(!run.arrived){point=driving?park:truck;name=driving?'WESTGATE PLAZA':'YOUR WORK TRUCK'}else if(!run.talked){point=w.manager;name='JORDAN / CHECK IN'}else if(!run.onRoof){point=hatch;name='ROOF ACCESS'}else if(currentContext?.f){point=currentContext.f;name='INSPECT DETAIL'}if(point){let py=run.onRoof?w.roofY+1.4:3.5,p=r.project([point.x,py,point.z]);$('pin').classList.toggle('hidden',!p.visible||p.y<65);$('pin').style.left=p.x+'px';$('pin').style.top=p.y+'px';$('pinText').textContent=name+' · '+Math.round(dist(driving?truck:player,point))+'m'}else $('pin').classList.add('hidden')}
 radar();}
 // Unified pointer controls: independent joystick, camera and brake pointers.
 const joyEl=$('joystick');function moveJoy(e){const b=joyEl.getBoundingClientRect(),rad=b.width*.34;let x=e.clientX-b.left-b.width/2,y=e.clientY-b.top-b.height/2,l=Math.hypot(x,y);if(l>rad){x=x/l*rad;y=y/l*rad}joy.x=x/rad;joy.y=y/rad;$('stick').style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`}
 joyEl.addEventListener('pointerdown',e=>{if(modal||joy.id!==null)return;e.preventDefault();joy.id=e.pointerId;joyEl.setPointerCapture(e.pointerId);moveJoy(e)});joyEl.addEventListener('pointermove',e=>{if(e.pointerId===joy.id){e.preventDefault();moveJoy(e)}});function releaseJoy(e){if(e.pointerId!==joy.id)return;joy.id=null;joy.x=joy.y=0;$('stick').style.transform='translate(-50%,-50%)'}for(const type of ['pointerup','pointercancel','lostpointercapture'])joyEl.addEventListener(type,releaseJoy);
 $('game').addEventListener('pointerdown',e=>{if(modal||!started||cameraPointer)return;if(e.pointerType==='touch'&&e.clientX<innerWidth*.32&&!photoMode)return;cameraPointer={id:e.pointerId,x:e.clientX,y:e.clientY};$('game').setPointerCapture(e.pointerId)});$('game').addEventListener('pointermove',e=>{if(cameraPointer?.id!==e.pointerId)return;let dx=e.clientX-cameraPointer.x,dy=e.clientY-cameraPointer.y;cameraPointer.x=e.clientX;cameraPointer.y=e.clientY;if(photoMode)photoYaw-=dx*.008;else{camYaw-=dx*.007;camPitch=clamp(camPitch+dy*.004,.18,.95)}dragTime=performance.now()});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('game').addEventListener(type,e=>{if(cameraPointer?.id===e.pointerId)cameraPointer=null});
 $('brake').addEventListener('pointerdown',e=>{e.preventDefault();braking=true;auto=false;$('brake').setPointerCapture(e.pointerId)});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('brake').addEventListener(type,()=>braking=false);
 addEventListener('keydown',e=>{if(modal){if(e.code==='Escape'&&!run?.complete){e.preventDefault();closeSheet()}if(e.code==='Tab'){let b=[...$('sheet').querySelectorAll('button,textarea')],first=b[0],last=b[b.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}return}if(['Tab','Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;keys[e.code]=true;if(e.code==='KeyE')interact();if(e.code==='Tab')report();if(e.code==='Escape')pause();if(e.code==='KeyF'&&run?.onRoof){if(photoMode){photoMode=false;focus=null}else if(context()?.type==='inspect')interact()}});addEventListener('keyup',e=>keys[e.code]=false);
 $('start').onclick=()=>start(false);$('continue').onclick=()=>start(true);$('action').onclick=interact;$('pause').onclick=pause;$('reportButton').onclick=report;$('cancelCamera').onclick=()=>{photoMode=false;focus=null;resetInput()};$('route').onclick=()=>{if(run.mode!=='drive')return;auto=!auto;if(auto){routeIndex=0;while(routeIndex<route.length-1&&truck.x>route[routeIndex].x+2)routeIndex++;toast('Auto drive on. Touch the thumbstick to take over.')}};$('sound').onclick=()=>{profile.sound=!profile.sound;audioInit();store(PROFILEKEY,profile);updateStats();chime()};
 function resize(){resetInput();r.resize()}addEventListener('resize',resize);if(window.visualViewport)visualViewport.addEventListener('resize',resize);addEventListener('pagehide',save);addEventListener('blur',()=>{resetInput();save()});document.addEventListener('visibilitychange',()=>{resetInput();if(document.hidden){save();if(started&&!modal&&!run.complete)pause();if(engineGain)engineGain.gain.value=0}});$('game').addEventListener('webglcontextlost',e=>{e.preventDefault();save();fail(new Error('The phone paused its 3D graphics. Your last saved progress is safe. Tap TRY AGAIN to reload.'))});
 let frame=0;function loop(now){const dt=Math.min(.04,(now-lastFrame)/1000);lastFrame=now;if(!document.hidden){clock+=dt;if(started&&!modal&&!run.complete&&!photoMode){run.seconds=(Number(run.seconds)||0)+dt;advance(dt)}setCamera(started?1-Math.exp(-dt*9):1);w.bird.y=w.roofY+Math.max(0,Math.sin(clock*2.1))*.06;w.bird.rx=Math.sin(clock*1.6)*.14;w.playerShadow.x=player.x;w.playerShadow.z=player.z;w.playerShadow.y=(run?.onRoof?w.roofY:.1)+.015;w.playerShadow.visible=player.visible;w.truckShadow.x=truck.x;w.truckShadow.z=truck.z;w.truckShadow.y=.14;w.truckShadow.yaw=truck.yaw;r.render(w.nodes,eye,target,innerWidth<innerHeight?63:54);if(frame++%3===0)hud();if(toastUntil&&now>toastUntil){$('toast').classList.remove('show');toastUntil=0}if(started&&now-lastSave>2500){save();lastSave=now}if(engineGain&&audio){engineGain.gain.setTargetAtTime(profile.sound&&started&&!modal&&run.mode==='drive'?.017+Math.abs(speed)*.001:0,audio.currentTime,.12);engineOsc.frequency.setTargetAtTime(47+Math.abs(speed)*6,audio.currentTime,.1)}}requestAnimationFrame(loop)}
 r.pixelCap=profile.low?1:1.5;r.resize();updateStats();$('start').disabled=false;$('start').textContent='START YOUR SHIFT →';$('introHelp').textContent=touch?'Thumbstick to move · Drag the world to look':'WASD to move · Drag to look · E to interact';if(saved&&!saved.complete)$('continue').classList.remove('hidden');requestAnimationFrame(loop);
 if(new URLSearchParams(location.search).has('qa'))window.__ROOFTOP={snapshot:()=>JSON.parse(JSON.stringify({version:V,started,modal,photoMode,focus:focus?.id,run,player:{x:player.x,y:player.y,z:player.z,yaw:player.yaw},truck:{x:truck.x,z:truck.z,yaw:truck.yaw},camYaw,speed,auto,context:context()?.type,joystick:joy,evidence:[...photos.keys()],profile,drawCalls:r.calls,viewport:[r.canvas.width,r.canvas.height]}))};
}catch(e){console.error(e);fail(e)}
})();
