/* ROOFTOP 0.33 — hands-on seam weld: touch drag control, probe verification, visible repaired lap + field reward. */
'use strict';
((g)=>{
 const SEAM={x:43,z:-30};
 const REWARD_CASH=110;
 const REWARD_REP=1;
 const PROBES=3;
 const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
 const dist=(a,b)=>a&&b?Math.hypot((a.x||0)-(b.x||0),(a.z||0)-(b.z||0)):Infinity;
 const popcount=n=>{n=Number(n)||0;let c=0;while(n){c+=n&1;n>>>=1}return c};
 const probeMask=()=>((1<<PROBES)-1);
 function repairReady(s){const r=s?.run,f=r?.findings?.seam,x=r?.seamRepairV33;return !!(s?.started&&r?.onRoof&&!r.complete&&f?.rec==='repair'&&!x?.complete)}
 function qualityFor({progress=0,offTrack=0,stalls=0}={}){const p=clamp(progress),line=clamp(1-(Number(offTrack)||0)*1.35),flow=clamp(1-(Number(stalls)||0)*.18);return Math.round(clamp(p*.55+line*.30+flow*.15)*100)}
 g.ROOFTOP_V33_HELPERS={SEAM,REWARD_CASH,REWARD_REP,PROBES,clamp,dist,popcount,probeMask,repairReady,qualityFor};
 const previous=g.createRoofUpgrades;
 if(typeof previous!=='function'||typeof document==='undefined')return;
 g.createRoofUpgrades=function(api){
  const base=previous(api)||{},$=id=>document.getElementById(id),state=()=>api.get(),{world,renderer}=api;
  let button=null,status=null,repairNodes=[],open=false,drag=null,lastNear=false,lastDone=false,lastStamp='',observer=null,audioCtx=null;
  function ensureRun(){const r=state().run;if(!r)return null;if(!r.seamRepairV33||r.seamRepairV33.version!==1)r.seamRepairV33={version:1,progress:0,offTrack:0,stalls:0,quality:0,probeMask:0,passComplete:false,complete:false,banked:false};const x=r.seamRepairV33;x.progress=clamp(Number(x.progress)||0);x.offTrack=Math.max(0,Number(x.offTrack)||0);x.stalls=Math.max(0,Number(x.stalls)||0);x.quality=Math.max(0,Math.min(100,Math.round(Number(x.quality)||0)));x.probeMask=Math.max(0,Math.min(probeMask(),Number(x.probeMask)||0));return x}
  function vibrate(p){try{navigator.vibrate?.(p)}catch{}}
  function tone(kind='tick'){if(!state().profile?.sound)return;try{const A=g.AudioContext||g.webkitAudioContext;if(!A)return;if(!audioCtx)audioCtx=new A();if(audioCtx.state==='suspended')audioCtx.resume();const now=audioCtx.currentTime,o=audioCtx.createOscillator(),gain=audioCtx.createGain();o.connect(gain);gain.connect(audioCtx.destination);o.type=kind==='weld'?'sawtooth':'sine';o.frequency.setValueAtTime(kind==='done'?560:kind==='weld'?145:320,now);if(kind==='done')o.frequency.exponentialRampToValueAtTime(780,now+.2);if(kind==='weld')o.frequency.linearRampToValueAtTime(205,now+.18);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(kind==='weld'?.018:.035,now+.018);gain.gain.exponentialRampToValueAtTime(.0001,now+(kind==='weld'?.16:.23));o.start(now);o.stop(now+(kind==='weld'?.18:.25))}catch{}}
  function ensureUI(){const hud=$('hud');if(!hud)return;if(!button){button=document.createElement('button');button.id='seamFixV33';button.className='seam-fix-v33 hidden';button.innerHTML='<small>FIELD REPAIR</small><b>HEAT-WELD SEAM</b><span id="seamFixProgressV33">WELD PASS · 0%</span>';button.onclick=openRepair;hud.appendChild(button)}if(!status){status=document.createElement('div');status.id='seamStatusV33';status.className='seam-status-v33 hidden';status.innerHTML='<span>MEMBRANE REPAIR</span><b>✓ LAP SEALED + PROBED</b>';hud.appendChild(status)}}
  function makeRepairProps(){if(world.v33SeamProps){repairNodes=world.v33SeamProps;return}try{const y=world.roofY+.145,nodes=[];let q=[];R3.box(q,0,.018,0,5.6,.035,.42,'#dce5de');R3.box(q,0,.045,.02,5.15,.025,.08,'#91a6a3');const strip=R3.node(renderer.mesh(q),SEAM.x,y,SEAM.z);strip.yaw=.06;strip.visible=false;world.nodes.push(strip);nodes.push(strip);let q2=[];R3.box(q2,0,.2,0,.75,.38,.34,'#345563');R3.cylinder(q2,-.36,.18,0,.12,.22,'#1d333f',10,.06);R3.box(q2,.43,.22,0,.48,.12,.1,'#f0d265');const tool=R3.node(renderer.mesh(q2),SEAM.x+3.2,world.roofY+.12,SEAM.z+.75);tool.yaw=Math.PI/2;tool.visible=false;world.nodes.push(tool);nodes.push(tool);world.v33SeamProps=nodes;repairNodes=nodes}catch{}}
  function syncScene(){makeRepairProps();const s=state(),x=ensureRun(),show=!!(s.started&&s.run?.onRoof&&!s.run.complete&&x?.complete);for(const n of repairNodes)n.visible=show}
  function bankReward(){const s=state(),x=ensureRun(),p=s.profile;if(!x?.complete||x.banked||!p)return false;const key='v33-seam:'+String(s.run?.id||'run');if(Array.isArray(p.paid)&&p.paid.includes(key)){x.banked=true;api.save?.();return false}p.cash=Math.max(0,(Number(p.cash)||0)+REWARD_CASH);p.rep=Math.min(100,Math.max(0,(Number(p.rep)||0)+REWARD_REP));if(!Array.isArray(p.badges))p.badges=[];if(!p.badges.includes('hot-lap'))p.badges.push('hot-lap');if(!Array.isArray(p.paid))p.paid=[];p.paid.push(key);p.paid=p.paid.slice(-40);x.banked=true;api.saveProfile?.();api.updateStats?.();api.save?.();return true}
  function syncHUD(force=false){ensureUI();const s=state(),x=ensureRun();if(!x)return;const ready=repairReady(s),near=ready&&dist(s.player,SEAM)<=4.7,done=!!x.complete,show=!!(near&&!s.photoMode&&!s.modal);button?.classList.toggle('hidden',!show);status?.classList.toggle('hidden',!(done&&s.run?.onRoof&&!s.run.complete&&!s.photoMode&&!s.modal));const label=$('seamFixProgressV33');if(label)label.textContent=x.passComplete?`PROBE CHECK · ${popcount(x.probeMask)} / ${PROBES}`:`WELD PASS · ${Math.round(x.progress*100)}%`;if(button)button.classList.toggle('ready-v33',x.passComplete);if(near&&!lastNear){button?.classList.remove('pop-v33');if(button){void button.offsetWidth;button.classList.add('pop-v33')}vibrate(6);api.toast?.('FIELD REPAIR AVAILABLE · Weld the documented open lap, then probe-check the repair.')}if(done&&!lastDone){status?.classList.remove('pop-v33');if(status){void status.offsetWidth;status.classList.add('pop-v33')}}lastNear=near;lastDone=done;if(force&&show){button.classList.remove('pop-v33');void button.offsetWidth;button.classList.add('pop-v33')}}
  function boardMarkup(x){const probes=[22,50,78].map((p,i)=>`<button class="probe-v33 ${(x.probeMask&(1<<i))?'checked-v33':''}" data-probe-v33="${i}" style="left:${p}%" aria-label="Probe check point ${i+1}"><i></i><span>${(x.probeMask&(1<<i))?'✓':'PROBE'}</span></button>`).join('');return `<section class="seam-game-v33"><div class="seam-meter-v33"><span><small>WELD CONTROL</small><b id="weldQualityV33">${x.quality||'—'}</b></span><i><em id="weldBarV33" style="width:${Math.round(x.progress*100)}%"></em></i><strong id="weldCueV33">${x.passComplete?'PASS COMPLETE':'DRAG TOOL LEFT → RIGHT'}</strong></div><div class="weld-board-v33 ${x.passComplete?'passed-v33':''}" id="weldBoardV33"><div class="membrane-v33"></div><div class="open-lap-v33"></div><div class="welded-lap-v33" id="weldedLapV33" style="width:${Math.round(x.progress*100)}%"></div><button id="welderV33" class="welder-v33" style="left:${4+clamp(x.progress)*88}%" aria-label="Drag heat welder across seam"><i></i><b></b><span></span></button><div class="sweet-v33">CONTROL ZONE</div>${x.passComplete?probes:''}</div><p class="seam-instruction-v33" id="seamInstructionV33">${x.passComplete?'Tap all three probe points to verify the simulated repair.':'Drag the welder steadily from left to right and keep it centered on the seam.'}</p><div class="seam-stats-v33"><span><small>CONTROL</small><b id="seamControlV33">${x.quality||0}%</b></span><span><small>PROBE CHECK</small><b id="seamProbeV33">${popcount(x.probeMask)} / ${PROBES}</b></span></div><p class="note">Arcade simulation only — no real-world heat settings, procedures, or safety instructions are represented.</p></section>`}
  function refreshBoard(x){const bar=$('weldBarV33'),lap=$('weldedLapV33'),tool=$('welderV33'),q=$('weldQualityV33'),control=$('seamControlV33'),cue=$('weldCueV33');if(bar)bar.style.width=Math.round(x.progress*100)+'%';if(lap)lap.style.width=Math.round(x.progress*100)+'%';if(tool)tool.style.left=(4+x.progress*88)+'%';if(q)q.textContent=x.quality||'—';if(control)control.textContent=(x.quality||0)+'%';if(cue)cue.textContent=x.progress<.18?'BUILD THE PASS':x.progress<.82?'KEEP IT CENTERED':x.progress<1?'FINISH THE LAP':'PASS COMPLETE'}
  function bindWelder(){const x=ensureRun(),board=$('weldBoardV33'),tool=$('welderV33');if(!x||!board||!tool||x.passComplete){bindProbes();return}let lastX=0,lastT=0;const end=()=>{if(!drag)return;drag=null;tool.classList.remove('dragging-v33');lastX=0;lastT=0;api.save?.()};tool.addEventListener('pointerdown',e=>{e.preventDefault();const rect=board.getBoundingClientRect();drag={id:e.pointerId,rect};tool.setPointerCapture?.(e.pointerId);tool.classList.add('dragging-v33');lastX=e.clientX;lastT=performance.now();vibrate(4);tone('weld')});tool.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();const now=performance.now(),r=drag.rect,p=clamp((e.clientX-r.left-r.width*.04)/(r.width*.88)),center=r.top+r.height*.53,off=Math.abs(e.clientY-center)/(r.height*.28),dx=Math.max(0,e.clientX-lastX),dt=Math.max(16,now-lastT);if(off>1)x.offTrack+=Math.min(.035,dt/1800);if(dx<1&&dt>110)x.stalls+=dt/1600;if(p>x.progress)x.progress=Math.min(1,Math.max(x.progress,p));x.quality=qualityFor(x);refreshBoard(x);lastX=e.clientX;lastT=now;if(Math.random()<.08)tone('weld');if(x.progress>=.995)completePass(x)});tool.addEventListener('pointerup',end);tool.addEventListener('pointercancel',end);tool.addEventListener('lostpointercapture',end);tool.addEventListener('contextmenu',e=>e.preventDefault())}
  function completePass(x){if(x.passComplete)return;x.progress=1;x.quality=qualityFor(x);x.passComplete=true;drag=null;api.save?.();tone('done');vibrate([7,14,7]);api.show?.('FIELD REPAIR / PROBE CHECK','Weld pass complete',boardMarkup(x),[{label:'BACK TO ROOF',secondary:true,fn:()=>{open=false;api.close?.();syncHUD()}}]);setTimeout(()=>{bindWelder();bindProbes()},0)}
  function bindProbes(){const x=ensureRun();if(!x?.passComplete)return;document.querySelectorAll('[data-probe-v33]').forEach(b=>b.onclick=()=>checkProbe(b,Number(b.dataset.probeV33)||0))}
  function checkProbe(button,i){const x=ensureRun();if(!x?.passComplete||x.complete||(x.probeMask&(1<<i)))return;x.probeMask|=(1<<i);button.classList.add('checked-v33');const span=button.querySelector('span');if(span)span.textContent='✓';const p=$('seamProbeV33');if(p)p.textContent=`${popcount(x.probeMask)} / ${PROBES}`;vibrate([5,9,5]);tone('tick');api.save?.();if(x.probeMask===probeMask())setTimeout(completeRepair,180)}
  function completeRepair(){const x=ensureRun();if(!x||x.complete)return;x.complete=true;x.quality=Math.max(70,qualityFor(x));bankReward();api.save?.();syncScene();tone('done');api.chime?.(true);vibrate([9,16,9,16,22]);api.show?.('FIELD REPAIR / COMPLETE','Open lap repaired',`<section class="seam-complete-v33"><div class="seam-check-v33">✓</div><small>WESTGATE PLAZA · MEMBRANE SEAM</small><h3>Weld pass sealed and probe-checked.</h3><p>The documented open lap now has a visible repaired state on the roof. Your original recommendation and evidence remain in the field report.</p><div class="seam-reward-v33"><span><small>WELD CONTROL</small><b>${x.quality}%</b></span><span><small>FIELD BONUS</small><b>+$${REWARD_CASH}</b></span></div><div class="seam-badge-v33">★ HOT LAP BADGE</div></section>`,[{label:'BACK TO ROOF',fn:()=>{open=false;api.close?.();syncHUD(true);api.toast?.('SEAM REPAIR LOGGED · Open lap sealed and probe-checked.')}}])}
  function openRepair(){const s=state(),x=ensureRun();if(!x||!repairReady(s))return;open=true;api.show?.('OPTIONAL FIELD REPAIR','Repair the documented open lap',boardMarkup(x),[{label:'BACK TO ROOF',secondary:true,fn:()=>{open=false;api.close?.();syncHUD()}}]);setTimeout(()=>{bindWelder();bindProbes()},0)}
  function overrideRadar(){const s=state(),x=ensureRun();if(!s.run?.onRoof||!repairReady(s)||x?.complete)return;const n=$('radarTargetNameV30'),rr=$('radarTargetRangeV30');if(n)n.textContent='OPTIONAL · REPAIR SEAM';if(rr)rr.textContent=`${Math.round(dist(s.player,SEAM))}M · FIELD REPAIR`}
  function injectCloseout(){const s=state(),body=$('sheetBody'),x=s.run?.seamRepairV33;if(!s.run?.complete||!x?.complete||!body||body.querySelector('.seam-closeout-v33'))return;const section=document.createElement('section');section.className='seam-closeout-v33';section.innerHTML=`<span>ON-SITE REPAIR</span><b>✓ OPEN LAP SEALED</b><small>Probe-checked · ${x.quality}% control · +$${REWARD_CASH} field bonus</small>`;body.appendChild(section)}
  function onStart(){base.onStart?.();ensureRun();ensureUI();makeRepairProps();syncScene();lastNear=false;lastDone=false;lastStamp='';syncHUD()}
  function recorded(f){base.recorded?.(f);if(f?.id==='seam'&&state().run?.findings?.seam?.rec==='repair')setTimeout(()=>api.toast?.('SEAM REPAIR UNLOCKED · Walk back to the open lap for an optional field repair.'),380);syncHUD(true)}
  function hud(){base.hud?.();const s=state(),x=ensureRun();if(!x)return;const stamp=[s.run?.id,s.run?.onRoof,s.run?.complete,s.run?.findings?.seam?.rec,x.progress,x.passComplete,x.probeMask,x.complete,s.photoMode,s.modal].join('|');if(stamp!==lastStamp){lastStamp=stamp;syncHUD();syncScene();overrideRadar();setTimeout(injectCloseout,0)}}
  function frame(dt,t){base.frame?.(dt,t);syncHUD();overrideRadar();if(status&&!status.classList.contains('hidden'))status.style.setProperty('--seam-glow-v33',String(.5+.5*Math.sin(t*2.4)))}
  function finished(){base.finished?.();button?.classList.add('hidden');status?.classList.add('hidden');setTimeout(injectCloseout,0)}
  function garage(back){button?.classList.add('hidden');status?.classList.add('hidden');return base.garage?.(back)}
  function scoreCard(){return base.scoreCard?.()}function nextTarget(){return base.nextTarget?.()}function photoBlocked(eye,target){return base.photoBlocked?.(eye,target)||false}
  ensureUI();const sheet=$('sheet');if(sheet&&g.MutationObserver){observer=new MutationObserver(()=>injectCloseout());observer.observe(sheet,{childList:true,subtree:true})}
  try{if(new URLSearchParams(location.search).has('qa'))g.__ROOFTOP_V33={helpers:g.ROOFTOP_V33_HELPERS,ensureRun,openRepair,syncHUD,state:()=>state()}}catch{}
  return {...base,onStart,recorded,hud,frame,finished,garage,scoreCard,nextTarget,photoBlocked}
 };
})(typeof window!=='undefined'?window:globalThis);
